interface AdminOneAbbrMap {
    [index: string]: string
}

export const ADMIN_ONE_ABBR_MAP: AdminOneAbbrMap = {
    "Aguascalientes": "AGU",
    "Baja California": "BCN",
    "Baja California Sur": "BCS",
    "Campeche": "CAM",
    "Chiapas": "CHP",
    "Chihuahua": "CHH",
    "Coahuila": "COA",
    "Colima": "COL",
    "Mexico": "CMX",
    "Durango": "DUR",
    "Guanajuato": "GUA",
    "Guerrero": "GRO",
    "Hidalgo": "HID",
    "Jalisco": "JAL",
    "México": "MEX",
    "Michoacán": "MIC",
    "Morelos": "MOR",
    "Nayarit": "NAY",
    "Nuevo León": "NLE",
    "Oaxaca": "OAX",
    "Puebla": "PUE",
    "Querétaro": "QUE",
    "Quintana Roo": "ROO",
    "San Luis Potosí": "SLP",
    "Sinaloa": "SIN",
    "Sonora": "SON",
    "Tabasco": "TAB",
    "Tamaulipas": "TAM",
    "Tlaxcala": "TLA",
    "Veracruz": "VER",
    "Yucatán": "YUC",
    "Zacatecas": "ZAC",
    "aguascalientes": "AGU",
    "baja california": "BCN",
    "baja california sur": "BCS",
    "campeche": "CAM",
    "chiapas": "CHP",
    "chihuahua": "CHH",
    "coahuila": "COA",
    "colima": "COL",
    "mexico": "CMX",
    "durango": "DUR",
    'distrito federal': 'Distrito Federal',
    "guanajuato": "GUA",
    "guerrero": "GRO",
    "hidalgo": "HID",
    "jalisco": "JAL",
    "méxico": "MEX",
    "michoacán": "MIC",
    "michoacan": "MIC",
    "morelos":  "MOR",
    "nayarit":  "NAY",
    "nuevo león": "NLE",
    "nuevo leon": "NLE",
    "oaxaca": "OAX",
    "puebla": "PUE",
    "querétaro": "QUE",
    "queretaro": "QUE",
    "quintana Roo": "ROO",
    "san luis potosí" : "SLP",
    "san luis potosi" : "SLP",
    "sinaloa": "SIN",
    "sonora": "SON",
    "tabasco": "TAB",
    "tamaulipas": "TAM",
    "tlaxcala": "TLA",
    "veracruz": "VER",
    "yucatán":  "YUC",
    "yucatan":  "YUC",
    "zacatecas":  "ZAC",
    "Alberta": "AB",
    "British Columbia": "BC",
    'Manitoba': "MB",
    'New Brunswick': "NB",
    'Northwest Territories': "NT",
    'Newfoundland and Labrador': "NL",
    "Nova Scotia": "NS",
    "Nunavat": "NU",
    "Ontario": "ON",
    'Prince Edward Island': "PE",
    'Québec': "QC",
    'Saskatchewan': "SK",
    "Yukon": "YT",
    'alberta': 'AB',
    'british columbia': 'BC',
    'nationalparken': 'Nationalparken',
    'new brunswick': 'NB',
    'newfoundland and labrador': 'NL',
    'newfoundland': 'NL',
    'labrador': 'NL',
    'northwest territories': 'NT',
    'nova scotia': 'NS',
    'nunavut': 'NU',
    'kommune kujalleq': 'Kommune Kujalleq',
    'kommuneqarfik sermersooq': 'Kommuneqarfik Sermersooq',
    'manitoba': 'MB',
    'ontario': 'ON',
    'pituffik': 'Pituffik',
    'prince edward island': 'PE',
    '1aasuitsup kommunia': 'Qaasuitsup Kommunia',
    'qeqqata kommunia': 'Qeqqata Kommunia',
    'québec': 'QC',
    'quebec': 'QC',
    'saskatchewan': 'SK',
    'arkansas': 'AR',
    'district of columbia': 'DC',
    'delaware': 'DE',
    'florida': 'FL',
    'georgia': 'GA',
    'kansas': 'KS',
    'louisiana': 'LA',
    'maryland': 'MD',
    'missouri': 'MO',
    'mississippi': 'MS',
    'north carolina': 'NC',
    'oklahoma': 'OK',
    'south carolina': 'SC',
    'tennessee': 'TN',
    'texas': 'TX',
    'west virginia': 'WV',
    'alabama': 'AL',
    'connecticut': 'CT',
    'iowa': 'IA',
    'illinois': 'IL',
    'indiana': 'IN',
    'maine': 'ME',
    'michigan': 'MI',
    'minnesota': 'MN',
    'nebraska': 'NE',
    'new hampshire': 'NH',
    'new jersey': 'NJ',
    'new york': 'NY',
    'ohio': 'OH',
    'rhode island': 'RI',
    'vermont': 'VT',
    'wisconsin': 'WI',
    'california': 'CA',
    'colorado': 'CO',
    'new mexico': 'NM',
    'nevada': 'NV',
    'utah': 'UT',
    'arizona': 'AZ',
    'idaho': 'ID',
    'montana': 'MT',
    'north dakota': 'ND',
    'oregon': 'OR',
    'south dakota': 'SD',
    'washington': 'WA',
    'wyoming': 'WY',
    'hawaii': 'HI',
    'alaska': 'AK',
    'kentucky': 'KY',
    'massachusetts': 'MA',
    'pennsylvania': 'PA',
    'virginia': 'VA',
    'Arkansas' : 'AR',
    'District of Columbia': 'DC',
    "Delaware": 'DE',
    "Florida": 'FL',
    "Georgia": 'GA',
    'Kansas': 'KS',
    "Louisiana": 'LA',
    "Maryland": 'MD',
    "Missouri": 'MO',
    "Mississippi": 'MS',
    "North Carolina": 'NC',
    'Oklahoma': 'OK',
    "South Carolina": 'SC',
    "Tennesse": 'TN',
    "Texas": 'TX',
    "West Virginia": 'WV',
    "Alabama": 'AL',
    'Connecticut': 'CT',
    'Iowa': 'IA',
    "Illinois": 'IL',
    "Indiana": 'IN',
    "Maine": 'ME',
    "Michigan": 'MI',
    "Minnesota": 'MN',
    "Nebraska": 'NE',
    "New Hampshire": 'NH',
    "New Jersey": 'NJ',
    "New York": 'NY',
    "Ohio": 'OH',
    "Rhode Island": 'RI',
    "Vermont": 'VT',
    "Wisconsin": 'WI',
    "California" : 'CA',
    "Colorado": 'CO',
    "New Mexico": 'NM',
    "Nevada": 'NV',
    "Utah": 'UT',
    "Arizona": 'AZ',
    "Idaho": 'ID',
    "Montana": 'MT',
    "North Dakota": 'ND',
    "Oregon": 'OR',
    "South Dakota": 'SD',
    "Washington": 'WA',
    "Wyoming": 'WY',
    "Hawaii": 'HI',
    'Alaska': 'AK',
    'Kentucky': 'KY',
    'Massachusetts': 'MA',
    'Pennsylvania': 'PA',
    'Virginia': 'VA',
}

export const abbreviateAdminOne = (value: string) => {
    if(ADMIN_ONE_ABBR_MAP.hasOwnProperty(value)){
        return ADMIN_ONE_ABBR_MAP[value];
    }else {
        return value;
    }
}